provider:
  name: faas
  gateway: http://faas.ae24.space:8080
  # gateway: http://localhost:8081

functions:
  get-avatar:
    lang: python
    handler: ./GetAvatar
    image: alexellis/faas-get-avatar:0.2

  fanclub:
    lang: python
    handler: ./Fanclub
    image: alexellis/faas-fanclub:0.2

  myassistant:
    lang: node
    handler: ./myassistant
    image: alexellis/faas-myassistant:0.2

  payroll:
    lang: node
    handler: ./payroll
    image: alexellis/faas-payroll:0.2
